resource_registry:
  OS::TripleO::DeployedServer::ControlPlanePort: OS::Neutron::Port

{% for role in roles %}
  OS::TripleO::{{role.name}}::Net::SoftwareConfig: OS::Heat::None
{% endfor %}

parameter_defaults:
  EnablePackageInstall: True
{% for role in roles %}
  {{role.name}}NetworkConfigTemplate: 'templates/net_config_static_bridge.j2'
{% endfor %}
